#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
#@ load("@ytt:assert", "assert")

#@ registry_host = data.values.app_image.split("/", 1)[0]

apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: #@ data.values.namespace
type: kubernetes.io/dockerconfigjson
stringData:
  #@ registry_auth = base64.encode("{}:{}".format(data.values.registry_username, data.values.registry_password))
  #@ registry_creds = {"username": data.values.registry_username, "password": data.values.registry_password, "auth": registry_auth}
  .dockerconfigjson: #@ json.encode({"auths": {registry_host: registry_creds}})